### ISSUE TITLE
Question, comments on hardware

### ISSUE THREAD

**Issue by Findus76** [sascha432/trailing_edge_dimmer#2]
Question
I am in the process of designing a dimmer, both hardware and software. Your project is clearly interesting as a starting point.
- Having ESP32. Can the ATmegan be skipped, or is it needed for the realtime feature?
- Which schematic versions do you recommend to start from, for both zirocrossing and transistor control?

**Comment by sascha432** [comment]
I would not recommend to use the ESP32, since it is not 100% stable and you would need a lot experience in RTOS to dedicate the second core to the dimmer for precise timings/mutex locks etc. And it will probably require some assembler code as well, I do not think the framework is able to handle anything in the micro second range. The single core is not suitable at all.

In case you use my zero crossing, its highly recommended to use my code as well since it has filters and predictive zero crossing detection to avoid any misfires that are not filtered by the hardware. AC turning on, or vacuum cleaner.. might lead to flickering lights. Due to the low amount of power it requires its also pretty sensitive without software filtering.

https://oshwlab.com/sascha23095123423/iot_1ch_dimmer_copy_copy_copy
or
https://oshwlab.com/sascha23095123423/iot-4-channel-dimmer-with-pm

You can copy the parts you need for your version of the dimmer. But using the AVR you got it all and the code is stable (2.2.2).
There is a lot ways to control the mains power stage (mosfets, mosfets with a driver, mosfets controlled by the opto coupler directly, triacs or even simple transistors with diodes for low power)
